# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: db
spec: 
  clusterIP: None
  selector:
    app: mysql
    project: expense
    tier: db
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
#Normal Service

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: db
spec: 
  selector:
    app: mysql
    project: expense
    tier: db
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
