apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # These labels for deployment resource. 
  labels:
    app: frontend
    tier: web
    purpose: expense
spec: 
  # Modify the replicas number according to our use case.
  replicas: 1
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: frontend
      tier: web
      purpose: expense
  # Pod Template
  template:
    metadata:
      labels: 
        app: frontend
        tier: web
        purpose: expense
    spec: 
      volumes:
      - name: nginx
        configMap:
          name: nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: nginx
        image: joindevops/frontend:{{ .Values.deployment.version }} 
        resources:
          requests:
            memory: "69Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080 
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true   