apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # These labels for deployment resource. 
  labels:
    app: backend
    tier: backend
    purpose: expense
spec: 
  # Modify the replicas number according to our use case.
  replicas: 1
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: backend
      tier: backend
      purpose: expense
  # Pod Template
  template:
    metadata:
      labels: 
        app: backend
        tier: backend
        purpose: expense
    spec: 
      containers:
      - name: backend
        image: joindevops/backend: {{ .Values.deployment.version}}   
        envFrom:
        - configMapRef:
            name: backend     